//! Low-level FFI bindings to SPDK (Storage Performance Development Kit)
//!
//! This crate provides raw bindings generated by bindgen from SPDK headers.
//! For a safe, ergonomic API, use the `spdk-io` crate instead.
//!
//! # Building
//!
//! Requires SPDK to be installed and `PKG_CONFIG_PATH` set:
//!
//! ```bash
//! export PKG_CONFIG_PATH=/opt/spdk/lib/pkgconfig:$PKG_CONFIG_PATH
//! cargo build
//! ```

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(improper_ctypes)]
#![allow(unsafe_op_in_unsafe_fn)]
#![allow(unnecessary_transmutes)]
#![allow(clippy::all)]

// Include the generated bindings
include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_bindings_exist() {
        // Basic sanity check that bindings were generated
        // Just verify some types exist
        let _: spdk_bdev_io_type = spdk_bdev_io_type_SPDK_BDEV_IO_TYPE_READ;
    }
}
